# Usa una imagen oficial de Node.js como base
FROM node:20

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /usr/src/app

# Copia solo package.json y package-lock.json primero
COPY package*.json ./

# Instala las dependencias dentro del contenedor
RUN npm install

# Luego copia el resto del código
COPY . .

# Expone el puerto de la aplicación
EXPOSE 3101

# Comando para ejecutar la aplicación
CMD ["node", "app.js"]
